server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be10_team1_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project_be10_team1
    password: N(zwIEW9ge2O3yXO

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

    # 외부 서비스 API
book-api:
  url: http://localhost:10304/

user-api:
  url: http://localhost:10303/