### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###



GET localhost:10305/order/guest/order-history/20250707121010-1111100000?contact=010-9876-5432
Accept: application/json


###

GET localhost:10305/order/member/orders/history?page=0&size=10
X-USER-ID: 2
Accept: application/json

###
