### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###



GET localhost:10305/order/guest/order-history/20250707121010-1111100000?contact=010-9876-5432
Accept: application/json


###

GET localhost:10305/order/member/orders/history?page=0&size=10
X-USER-ID: 2
Accept: application/json

###

GET localhost:10305/order/member/orders/1
X-USER-ID:1
Accept: application/json

###

GET localhost:10305/order/admin/orders?status=Pending&page=1&size=10
Accept: application/json

###

GET localhost:10305/order/admin/orders/3
Accept: application/json

###

PATCH localhost:10305/order/admin/orders/1
Content-Type: application/json

{
  "orderStatus": "Delivered"
}

###

GET localhost:10305/api/order/member/init-member-info/books/60
X-USER-ID: 2
Accept: application/json

###

GET localhost:10305/api/order/member/init-member-info/books/60
X-USER-ID: 2
Accept: application/json

###